### ISSUE TITLE
error when using tkmatrix for star with radius > 1 solar radius

### ISSUE THREAD

**Issue by toribonidie** [PlanetHunters/tkmatrix#29]
Hi!

Sorry to bother you again, but I am wondering if tkmatrix is compatible with stars greater than 1 solar radius. I was hoping to use this to do transit injection and recovery for planets around red clump stars, but I get the error: `ValueError: radius_1 argument out of range` . I looked into the lc.py file in ellc, and it looks like it raises an error any time the star has a radius greater than 1.

Have you tried using tkmatrix for stars with radii greater than 1? If not, I would suggest adding this to the readme! 

Thanks so much.

**Comment by martindevora** [comment]
can you share the properties.yaml file you are using? That'd help to reproduce it. I will give it a try in the meantime with any other properties I can come with as I never tried R > 1R_sun.

**Comment by martindevora** [comment]
Also, can you share the entire traceback of the exception?

**Comment by martindevora** [comment]
BTW: The code in ellc does this:
```
  if (radius_1 <= 0) or (radius_1 > 1):
    raise ValueError("radius_1 argument out of range")
 ```
 but in ellc the star radius is given in in `units of the semi-major axis of the system`. That is, `R_star.to_au / semi_major_axis`. The `semi_major_axis` depends on the `star mass` and the `planet period`. So it might be that the star radius is greater than the distance to the planet (`radius_1 > 1`), which would mean that the planet could not exist.

What was your minimum period in the properties.yaml ? Please share it to have a further look.

Regards.

**Comment by toribonidie** [comment]
Hi!

Thank you again for such a quick response. I think that the period does seem to be the issue, and it looks like I picked a weird system to start with. I am looking at TIC 15932677, a red clump star with a potential planet transiting every 1.4 days. So I let my period range go down to 1 day and masked the planet candidate (file attached). However, if this star actually has the radius predicted by lightkurve (10.8 Rsun) , this system does not even seem possible. I am attaching the .yaml file and traceback but I think you're right and I should just pick another star and pick a different minimum period. Not sure what is going on with this system.

Thanks again for the help
[nohup.out.txt](https://github.com/PlanetHunters/tkmatrix/files/10787457/nohup.out.txt)
[TIC15932677.yaml.txt](https://github.com/PlanetHunters/tkmatrix/files/10787458/TIC15932677.yaml.txt)

**Comment by martindevora** [comment]
First of all: 
* When you want to use the `KNOWN_TRANSITS` key in MATRIX, you need to provide P (Period), D (Duration) and T0 (epoch). I see you only provided P and D, so your analysis will probably be masking your known candidate incorrectly.
* It seems that the star mass is not provided by the MAST and hence MATRIX assumes 0.1M_sun. That is almost 99% sure the source of your problem here. Try to find it in the logs. When this happens, you might try manually injecting your own star information. 
* Given the things I state in the previous two points, I attach a suggestion of a new properties file:
```
TARGET: "TIC 15932677"
SECTORS: [44]
EXPOSURE_TIME: 120
MIN_PERIOD: 1.4 # I saw that this is approximately the first period where the planet would not be inside the star radius
MAX_PERIOD: 30
STEPS_PERIOD: 10
MIN_RADIUS: 2
MAX_RADIUS: 3.5
STEPS_RADIUS: 10
PHASES: 1
DETREND_WS: 1.0 # I changed this becase 0.5 days is a small detrending window size for such a big star, where the transits might take even 1 day long for medium periods.
CPUS: 40
KNOWN_TRANSITS:
  - P: 1.436896
    D: 0.098625
    T0: 2500.871
OVERSAMPLING: 1
STAR:
  "TIC 15932677":
    MASS: 10.0
    MASS_LOWER_ERROR: 0.5
    MASS_UPPER_ERROR: 0.5
    RADIUS: 10.85
    RADIUS_LOWER_ERROR: 0.2
    RADIUS_UPPER_ERROR: 0.2
    TEFF: 4876
```
* Despite all of the above, `ellc` seems to be generating all NaN curves for all the scenarios, so the MATRIX execution won't be helpful here. I'll keep investigating about what I can do to make it work, but this is typically due to physical conditions (we are frequently finding that ellc was generating all Nan curves when our scenarios were in the Roche Sphere, but I don't know if this might be the case).


Second, I've tried your target with the pipeline that we develop together in the Granada and LIège Universities: https://github.com/franpoz/SHERLOCK. The results show:
* The odd and even transits have separately enough significance, which means that the target has some odds to be an eclipsing binary (even though that doesn't discard a giant planet)
* There is an official Data Validation Report from the SPOC (which SHERLOCK downloads when vetting a given candidate). I attach it here. It doesn't have high scores for a likely planet but it seems that it didn't find it good enough to promote it as a candidate.
[tess2021285162058-s0044-s0044-0000000015932677-00536_dvr.pdf](https://github.com/PlanetHunters/tkmatrix/files/10788020/tess2021285162058-s0044-s0044-0000000015932677-00536_dvr.pdf)

I have no explanation about the star radius, but it seems that there are other measurements from other users in ExoFop that  substantially differ from the 10.8 M_sun.

**Comment by toribonidie** [comment]
Thank you so much, this is very helpful!

**Comment by martindevora** [comment]
Hello, good morning. I just found out the reason causing all NaNs. It seems that the MAST is not providing limb darkening coefficients, hence `ellc` is not able to return anything. You can inject them in the MATRIX properties like this:
```
TARGET: "TIC 15932677"
SECTORS: [44]
EXPOSURE_TIME: 120
MIN_PERIOD: 1.4 # I saw that this is approximately the first period where the planet would not be inside the star radius
MAX_PERIOD: 30
STEPS_PERIOD: 10
MIN_RADIUS: 2
MAX_RADIUS: 3.5
STEPS_RADIUS: 10
PHASES: 1
DETREND_WS: 1.0 # I changed this becase 0.5 days is a small detrending window size for such a big star, where the transits might take even 1 day long for medium periods.
CPUS: 40
KNOWN_TRANSITS:
  - P: 1.436896
    D: 0.098625
    T0: 2500.871
OVERSAMPLING: 1
STAR:
  "TIC 15932677":
    MASS: 10.0
    MASS_LOWER_ERROR: 0.5
    MASS_UPPER_ERROR: 0.5
    RADIUS: 10.85
    RADIUS_LOWER_ERROR: 0.2
    RADIUS_UPPER_ERROR: 0.2
    TEFF: 4876
    LD_COEFFICIENTS: [0.25, 0.64] # Replace with your common values for red giants
```

And then MATRIX will have some models to run!

NOTE: I will make MATRIX to exit if there are no limb-darkening parameters in the next version, as they seem to be required by ellc.
NOTE 1: Don't know if you already noticed, but this star was also observed in the K2 mission (SHERLOCK told me that).

**Comment by martindevora** [comment]
Hello again,

I've already published a new MATRIX version that:
* Breaks if there are no limb darkening parameters
* Breaks if your min period orbit is shorter than the star radius, advising the user about the minimum period that would meet the requirements for the given star mass and radius.

**Comment by toribonidie** [comment]
Thank you so much for all of your help! I was able to run it successfully on TIC 15932677 and a couple other red clump stars. If there is anything I can do to help going forward, please reach out!

**Comment by martindevora** [comment]
Thank you. I hope it helps with your research. Regards.
